version: '3'

services:
  gen:
    container_name: gen
    build: ./app
    restart: "on-failure" 
    env_file: ./config/gen/.env
    volumes:
      - .:/opt/gen/src:rw
      - static_volume:/home/gen/static
      - media_volume:/home/gen/media
    networks:
      - nginx_network
    command: /usr/local/bin/gunicorn GEN.asgi:application --workers 2 --bind :8000 --worker-class uvicorn.workers.UvicornWorker
    expose:
      - 8000

  nginx:
    image: nginx:1.19-alpine
    restart: "on-failure"  
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/home/gen/static
      - media_volume:/home/gen/media
    depends_on:
      - gen
    networks:
      - nginx_network


networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume: 
  media_volume: 
